version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Admin1234!
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-db.ci96iwo8wo1f.us-east-1.rds.amazonaws.com:3306/keycloakdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: Admin1234!
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_URL: "http://54.90.182.118:8080"
      KC_FRONTEND_URL: "http://54.90.182.118:8080"
    restart: always
